### ISSUE TITLE
cannot import jvectormap when upgrade jquery from 3.4.1 to 3.5.0

### ISSUE THREAD

**Issue by JohnSmith0602** [alex-pex/jvectormap#4]
I use jvectormap with webpack in this way,
``` javascript
import $ from 'jquery';
import 'jvectormap-next';
```
It works fine until I upgrade jquery from 3.4.1 to 3.5.0 for security reasons. After upgrade, the console throws the error 'Uncaught TypeError: jQuery.fn.vectorMap is not a function'

Since I use other jquery plugins like jquery-knob, and it works fine after upgrade. I compare the files and find the following diff:

File in [jquery-knob](https://github.com/aterrien/jQuery-Knob/blob/master/js/jquery.knob.js):
``` javascript
if (typeof exports === 'object') {
  // CommonJS
  module.exports = factory(require('jquery'));
}
```
File in [jvectormap](https://github.com/alex-pex/jvectormap/blob/master/jvectormap-next/src/jquery-jvectormap.js):
``` javascript
if (typeof exports === 'object') {
    // Node/CommonJS style for Browserify
    module.exports = factory;
}
```
After I change this file as jquery-knob does, it works fine too.

Is it OK if I submit a PR for this change?

**Comment by alex-pex** [comment]
Hello! Sorry for the delay, I didn't see Github notification

If you look at the https://github.com/alex-pex/jvectormap/blob/master/jvectormap-next/README.md you'll see you're doing it wrong.

You're supposed to link jvectormap-next with YOUR jquery dependency, like this:
```js
var $ = require('jquery');
// load jvectormap jquery plugin + map content
require('jvectormap-next')($);
```
or
```js
import $ from 'jquery';
import loadJvectorMap from 'jvectormap-next';
// load jvectormap jquery plugin + map content
loadJvectorMap($);
```
---
I was inspired by this file in the original sources https://github.com/bjornd/jvectormap/blob/a0e5497407946cabaad17124021ae70af8722b67/lib/jquery-mousewheel.js#L13

**Comment by JohnSmith0602** [comment]
@alex-pex thanks for the reply!
